// Generated by LiveScript 1.5.0
(function(){
  $(function(){
    $('#json, #code').keyup(function(){
      var out, e;
      try {
        out = nunjucks.renderString($('#code').val(), eval('(' + $('#json').val() + ')'));
        return $('#output').text(out);
      } catch (e$) {
        e = e$;
        return $('#output').text(e);
      }
    });
    return $('#json').trigger('keyup');
  });
}).call(this);