title: Useful JS Tools
# description: I failed my way to success
url: "https://dinhanhthi.github.io/"
baseurl: "tools"

title-separator: "-"

google_analytics: UA-58921685-1
fb_app_id: "1150663561751902"

timezone: "Europe/Paris"
markdown: kramdown
mathjax: true
kramdown:
  input: GFM
highlighter: rouge
permalink: /:title

plugins:
  - jemoji
  - jekyll-katex
  - jekyll-include-cache

sass:
  style: compact

exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
